name: CI
on:
  pull_request:
  push:
  schedule:
  - cron: '0 0 * * 0'
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        include:
          - java: 8
          - java: 11
    steps:
    - uses: actions/checkout@v3
    - uses: olafurpg/setup-scala@v14
      with:
        java-version: "adopt@1.${{ matrix.java }}"
    - uses: coursier/cache-action@v6
    - run: sbt -v
           "+mimaReportBinaryIssues"
           "+Test/compile"
           "+test"
